parameters:
#    zendesk.example.class: Malwarebytes\ZendeskBundle\Example

services:
#    zendesk.example:
#        class: %zendesk.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
