imports:
    - { resource: "@ZendeskBundle/Resources/config/api.yml" }

parameters:
    zendesk.apiservice.class: Malwarebytes\ZendeskBundle\Service\ApiService

services:
    zendesk.api:
        class: zendesk.apiservice.class
        arguments: [%api.apikey%, %api.user%, %api.subdomain%]
